### ISSUE TITLE
Build Failure when using the 'install' maven goal

### ISSUE THREAD

**Issue by kristinclemens** [dwtj/panini#22]
# Problem
In a local branch where I removed org.paninij.example.runtime, running the Maven goal 'clean install' or 'clean' then 'install' some times (not always) causes a build failure for PaniniJ Examples. David has apparently experienced something similar elsewhere, so this doesn't seem to be limited to my own local branch or the specific changes I made within it.

# Workaround
Use 'build' rather than 'install'.

# TODO
1. Determine steps which produce the error 100% of the time.
2. Determine why 'install' fails when 'build' does not.

**Comment by dwtj** [comment]
Using `build` on the `examples` maven submodule may work to eliminate certain bugs. I really don't know one way or the other. But I do know that it is important that we use the `install` goal when building the `capsule-generation` submodule: `install` adds the most up-to-date `capsule-generation` JAR to the local maven repository. During development, we will want the most recent JAR in place every time we build, because (for now) it is usually `capsule-generation` that we are modifying.

**Comment by kristinclemens** [comment]
I'm not sure this is actually a bug. It may be Working As Intended, unfortunately. After doing some poking around online, what _may_ be occurring is this: when `capsule-generation` JAR is already located in your local maven repository, maven "intelligently" uses that JAR to do code generation instead of building a new JAR.

If this is the case, we can use a separate maven goal to automatically delete the local JAR prior to doing anything else. This may already be built in, but if not then I'll need to look in to creating custom maven goals. Thoughts, @dwtj?

**Comment by kristinclemens** [comment]
Apparently it is actually a bug with the java compiler. For now just make sure you are always running mvn clean install, as running mvn install when it is already installed causes a java compiler exception.
