### ISSUE TITLE
Replace Use Of `PaniniPress.getBoxedReturnType()` with `Types.boxedClass()`

### ISSUE THREAD

**Issue by dwtj** [dwtj/panini#7]
Can we replace `org.paninij.apt.PaniniPress.getBoxedReturnType()` (a custom-made function) with `javax.lang.model.util.Types.boxedClass()` (a standard library function)?

**Comment by kristinclemens** [comment]
Could you give a quick example of what the function does? Here is the link to the library function directly:  http://docs.oracle.com/javase/8/docs/api/javax/lang/model/util/Types.html

Is it simply turning, say, an `int` in to an `Integer`?

**Comment by dwtj** [comment]
Exactly.

**Comment by kristinclemens** [comment]
Oh, huh. Yeah I don't see why not.

I propose we wrap the included method with our own rather than call it directly; this allows us to have a simple unit test for it.

(Note: I'm generally a fan of wrapping built-in methods in general. This helps with maintainability for when built-in methods inevitably become deprecated or otherwise change.)

**Comment by dwtj** [comment]
I agree with you in general, but maybe not in this case. We're talking about Oracle's implementation of the standard Java API:

- If it has bugs, it's not our job to make unit tests to find them out.
- There is no reason to expect this API to change.

However, there may be a need for a small wrapper to change the input/output types slightly. For example:

```
String ourBoxedClassWrapper(ExecutableElement method)
```

**Comment by kristinclemens** [comment]
Okay, before I answer further I think you're talking about a different problem that probably belongs in a different thread. I'll go with it, though.

In any case, we're expecting some `ExecutableElement method` to return a `java.lang.String` in this scenario?

**Comment by dwtj** [comment]
Yes, I think that might be a useful helper method. Check out the code for how we are currently using `getBoxedReturnType()`.

**Comment by kristinclemens** [comment]
A link would be awesome! :D

**Comment by dwtj** [comment]
[link](https://github.com/dwtj/panini/tree/capsule-generation/multiple-artifacts/capsule-generation/src/main/java/org/paninij/apt)

**Comment by kristinclemens** [comment]
As for the original issue:

The point is to keep our own code one step removed from built-in code, so that our code which implements the unboxing method doesn't have to ever care about the internals of that unboxing method. Ever. If we need to change it in the future (for example, maybe we decide it's faster to write our own way!), we only have to change it in one place: the wrapper function. It's just an element of modularization and information hiding.

For the initial issue:
So, in `org.paninij.util` for example:

	public static TypeElement getBoxedClass(PrimitiveType primitive) {
		return javax.lang.util.Types.getBoxedClass(primitive);
	}

I'll make another post here for the second issue. We're writing too much in PaniniPress already, I can tell you that much just from the quick digging I've done.

**Comment by kristinclemens** [comment]
Okay, I need to actually pull and use eclipse to check out where you're referencing these things before I can respond further.

**Comment by dwtj** [comment]
Another possibility would be to Kristin's idea to use an `enum` with a constructor.

**Comment by kristinclemens** [comment]
I am reminded of this enum with a constructor idea. Did we discard this idea? If not I'm going to move it to its own issue thread and provide a link here.

**Comment by dwtj** [comment]
The `getBoxedReturnType()` helper method was moved to `JavaModelInfo`. Some discussion in the past led to the conclusion that `Types.boxedClass()` would not be a useful replacement: `Types.boxedClass()` takes only primitives, so we would probably need to wrap it in our own helper method, and that helper method would end up looking just like the switch statement that is already implemented as part of `getBoxedReturnType()`.
